# coding: utf-8

"""
    IP RL BSP API

    IP RL BSP API for participation in capacity/energy market tenders.  # noqa: E501

    OpenAPI spec version: 3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.one_of_batch_operation_body import OneOfBatchOperationBody  # noqa: E501
from swagger_client.rest import ApiException


class TestOneOfBatchOperationBody(unittest.TestCase):
    """OneOfBatchOperationBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOneOfBatchOperationBody(self):
        """Test OneOfBatchOperationBody"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.one_of_batch_operation_body.OneOfBatchOperationBody()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
