# coding: utf-8

"""
    IP RL BSP API

    IP RL BSP API for participation in capacity/energy market tenders.  # noqa: E501

    OpenAPI spec version: 3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.bidding_api import BiddingApi  # noqa: E501
from swagger_client.rest import ApiException


class TestBiddingApi(unittest.TestCase):
    """BiddingApi unit test stubs"""

    def setUp(self):
        self.api = BiddingApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_bid(self):
        """Test case for delete_bid

        Deletes a simple, complex bid or a bid component  # noqa: E501
        """
        pass

    def test_get_bid(self):
        """Test case for get_bid

        Get a simple, complex bid or a complex bid component  # noqa: E501
        """
        pass

    def test_get_bids(self):
        """Test case for get_bids

        List submitted bids (optionally capacity or energy market)  # noqa: E501
        """
        pass

    def test_submit_bid(self):
        """Test case for submit_bid

        Submit a simple, complex bid or a complex bid component  # noqa: E501
        """
        pass

    def test_update_bid(self):
        """Test case for update_bid

        Updates a simple, complex bid or a bid component  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
