# coding: utf-8

"""
    IP RL BSP API

    IP RL BSP API for participation in capacity/energy market tenders.  # noqa: E501

    OpenAPI spec version: 3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.documents_api import DocumentsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestDocumentsApi(unittest.TestCase):
    """DocumentsApi unit test stubs"""

    def setUp(self):
        self.api = DocumentsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_document(self):
        """Test case for get_document

        Returns a document by its id.  # noqa: E501
        """
        pass

    def test_get_document_content(self):
        """Test case for get_document_content

        Returns the content of requested document as \"file download\"  # noqa: E501
        """
        pass

    def test_get_documents(self):
        """Test case for get_documents

        Result documents  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
