# coding: utf-8

"""
    IP RL BSP API

    IP RL BSP API for participation in capacity/energy market tenders.  # noqa: E501

    OpenAPI spec version: 3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.simple_bid import SimpleBid  # noqa: E501
from swagger_client.rest import ApiException


class TestSimpleBid(unittest.TestCase):
    """SimpleBid unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSimpleBid(self):
        """Test SimpleBid"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.simple_bid.SimpleBid()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
