# coding: utf-8

"""
    IP RL BSP API

    IP RL BSP API for participation in capacity/energy market tenders.  # noqa: E501

    OpenAPI spec version: 3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.product_name import ProductName  # noqa: E501
from swagger_client.rest import ApiException


class TestProductName(unittest.TestCase):
    """ProductName unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testProductName(self):
        """Test ProductName"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.product_name.ProductName()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
