# coding: utf-8

"""
    IP RL BSP API

    IP RL BSP API for participation in capacity/energy market tenders.  # noqa: E501

    OpenAPI spec version: 3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.batch_api import BatchApi  # noqa: E501
from swagger_client.rest import ApiException


class TestBatchApi(unittest.TestCase):
    """BatchApi unit test stubs"""

    def setUp(self):
        self.api = BatchApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_batch(self):
        """Test case for batch

        Submit batch requests  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
