# coding: utf-8

"""
    IP RL BSP API

    IP RL BSP API for participation in capacity/energy market tenders.  # noqa: E501

    OpenAPI spec version: 3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.tenders_api import TendersApi  # noqa: E501
from swagger_client.rest import ApiException


class TestTendersApi(unittest.TestCase):
    """TendersApi unit test stubs"""

    def setUp(self):
        self.api = TendersApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_tender(self):
        """Test case for get_tender

        Get tender  # noqa: E501
        """
        pass

    def test_get_tender_demand(self):
        """Test case for get_tender_demand

        Demand of tender  # noqa: E501
        """
        pass

    def test_get_tender_list(self):
        """Test case for get_tender_list

        List tenders (optionally capacity/energy market)  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
