# coding: utf-8

"""
    IP RL BSP API

    IP RL BSP API for participation in capacity/energy market tenders.  # noqa: E501

    OpenAPI spec version: 3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.bsp_api import BSPApi  # noqa: E501
from swagger_client.rest import ApiException


class TestBSPApi(unittest.TestCase):
    """BSPApi unit test stubs"""

    def setUp(self):
        self.api = BSPApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_backup_contracts(self):
        """Test case for get_backup_contracts

        Returns current backup contracts  # noqa: E501
        """
        pass

    def test_get_framework_contracts(self):
        """Test case for get_framework_contracts

        Current framework agreements  # noqa: E501
        """
        pass

    def test_get_pre_qualified_capacities(self):
        """Test case for get_pre_qualified_capacities

        Prequalified capacities.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
