# coding: utf-8

# flake8: noqa
"""
    IP RL BSP API

    IP RL BSP API for participation in capacity/energy market tenders.  # noqa: E501

    OpenAPI spec version: 3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

# import models into model package
from swagger_client.models.activation_type import ActivationType
from swagger_client.models.allocation_result_element import AllocationResultElement
from swagger_client.models.backup_contract import BackupContract
from swagger_client.models.balancing_service_provider import BalancingServiceProvider
from swagger_client.models.batch_operation import BatchOperation
from swagger_client.models.batch_operation_response import BatchOperationResponse
from swagger_client.models.batch_request import BatchRequest
from swagger_client.models.batch_response import BatchResponse
from swagger_client.models.batch_supported_http_method import BatchSupportedHttpMethod
from swagger_client.models.bid import Bid
from swagger_client.models.bid_group import BidGroup
from swagger_client.models.bid_identification import BidIdentification
from swagger_client.models.bid_modification import BidModification
from swagger_client.models.bid_submission import BidSubmission
from swagger_client.models.bid_submission_response import BidSubmissionResponse
from swagger_client.models.bid_tag import BidTag
from swagger_client.models.bid_type import BidType
from swagger_client.models.complex_bid import ComplexBid
from swagger_client.models.complex_bid_component import ComplexBidComponent
from swagger_client.models.conditional_linkage import ConditionalLinkage
from swagger_client.models.conditional_linkage_item import ConditionalLinkageItem
from swagger_client.models.connecting_zone import ConnectingZone
from swagger_client.models.contract_validity_period import ContractValidityPeriod
from swagger_client.models.country_code import CountryCode
from swagger_client.models.delivery_date import DeliveryDate
from swagger_client.models.demand import Demand
from swagger_client.models.demand_data import DemandData
from swagger_client.models.direction import Direction
from swagger_client.models.eic import EIC
from swagger_client.models.framework_agreement import FrameworkAgreement
from swagger_client.models.health import Health
from swagger_client.models.health_state import HealthState
from swagger_client.models.linkage_condition import LinkageCondition
from swagger_client.models.notification import Notification
from swagger_client.models.notification_reference import NotificationReference
from swagger_client.models.one_of_batch_operation_body import OneOfBatchOperationBody
from swagger_client.models.one_of_bid_submission import OneOfBidSubmission
from swagger_client.models.prequalified_capacity import PrequalifiedCapacity
from swagger_client.models.price import Price
from swagger_client.models.prices import Prices
from swagger_client.models.problem_details import ProblemDetails
from swagger_client.models.product_name import ProductName
from swagger_client.models.product_type import ProductType
from swagger_client.models.quantity import Quantity
from swagger_client.models.reserve_market import ReserveMarket
from swagger_client.models.resource_identification import ResourceIdentification
from swagger_client.models.result_document import ResultDocument
from swagger_client.models.simple_bid import SimpleBid
from swagger_client.models.technical_link_identification import TechnicalLinkIdentification
from swagger_client.models.technical_linkage import TechnicalLinkage
from swagger_client.models.tender import Tender
from swagger_client.models.tender_identification import TenderIdentification
from swagger_client.models.time_interval import TimeInterval
