# coding: utf-8

"""
    IP RL BSP API

    IP RL BSP API for participation in capacity/energy market tenders.  # noqa: E501

    OpenAPI spec version: 3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class BatchOperation(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'path': 'str',
        'method': 'BatchSupportedHttpMethod',
        'body': 'OneOfBatchOperationBody'
    }

    attribute_map = {
        'path': 'path',
        'method': 'method',
        'body': 'body'
    }

    def __init__(self, path=None, method=None, body=None):  # noqa: E501
        """BatchOperation - a model defined in Swagger"""  # noqa: E501
        self._path = None
        self._method = None
        self._body = None
        self.discriminator = None
        self.path = path
        self.method = method
        if body is not None:
            self.body = body

    @property
    def path(self):
        """Gets the path of this BatchOperation.  # noqa: E501

        A permitted relative BSP API v2 resource path.  # noqa: E501

        :return: The path of this BatchOperation.  # noqa: E501
        :rtype: str
        """
        return self._path

    @path.setter
    def path(self, path):
        """Sets the path of this BatchOperation.

        A permitted relative BSP API v2 resource path.  # noqa: E501

        :param path: The path of this BatchOperation.  # noqa: E501
        :type: str
        """
        if path is None:
            raise ValueError("Invalid value for `path`, must not be `None`")  # noqa: E501

        self._path = path

    @property
    def method(self):
        """Gets the method of this BatchOperation.  # noqa: E501


        :return: The method of this BatchOperation.  # noqa: E501
        :rtype: BatchSupportedHttpMethod
        """
        return self._method

    @method.setter
    def method(self, method):
        """Sets the method of this BatchOperation.


        :param method: The method of this BatchOperation.  # noqa: E501
        :type: BatchSupportedHttpMethod
        """
        if method is None:
            raise ValueError("Invalid value for `method`, must not be `None`")  # noqa: E501

        self._method = method

    @property
    def body(self):
        """Gets the body of this BatchOperation.  # noqa: E501

        Request body. Required for PATCH and POST operations.  # noqa: E501

        :return: The body of this BatchOperation.  # noqa: E501
        :rtype: OneOfBatchOperationBody
        """
        return self._body

    @body.setter
    def body(self, body):
        """Sets the body of this BatchOperation.

        Request body. Required for PATCH and POST operations.  # noqa: E501

        :param body: The body of this BatchOperation.  # noqa: E501
        :type: OneOfBatchOperationBody
        """

        self._body = body

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(BatchOperation, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, BatchOperation):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
