# coding: utf-8

"""
    IP RL BSP API

    IP RL BSP API for participation in capacity/energy market tenders.  # noqa: E501

    OpenAPI spec version: 3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class Bid(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'BidIdentification',
        'complex_bid_id': 'BidIdentification',
        'group_id': 'BidIdentification',
        'bid_type': 'BidType',
        'tender': 'TenderIdentification',
        'product_type': 'ProductType',
        'delivery_date': 'DeliveryDate',
        'market': 'ReserveMarket',
        'product_name': 'ProductName',
        'direction': 'Direction',
        'time_interval': 'TimeInterval',
        'connecting_zone': 'ConnectingZone',
        'resource_provider': 'EIC',
        'status': 'str',
        'receipt_timestamp': 'datetime',
        'revision_timestamp': 'datetime',
        'activation': 'ActivationType',
        'min_quantity': 'Quantity',
        'offered_quantity': 'Quantity',
        'accepted_quantity': 'Quantity',
        'prices': 'Prices',
        'technical_linkage': 'TechnicalLinkage',
        'conditional_linkage': 'ConditionalLinkage',
        'backup_for': 'BalancingServiceProvider',
        'tag': 'BidTag'
    }

    attribute_map = {
        'id': 'id',
        'complex_bid_id': 'complexBidId',
        'group_id': 'groupId',
        'bid_type': 'bidType',
        'tender': 'tender',
        'product_type': 'productType',
        'delivery_date': 'deliveryDate',
        'market': 'market',
        'product_name': 'productName',
        'direction': 'direction',
        'time_interval': 'timeInterval',
        'connecting_zone': 'connectingZone',
        'resource_provider': 'resourceProvider',
        'status': 'status',
        'receipt_timestamp': 'receiptTimestamp',
        'revision_timestamp': 'revisionTimestamp',
        'activation': 'activation',
        'min_quantity': 'minQuantity',
        'offered_quantity': 'offeredQuantity',
        'accepted_quantity': 'acceptedQuantity',
        'prices': 'prices',
        'technical_linkage': 'technicalLinkage',
        'conditional_linkage': 'conditionalLinkage',
        'backup_for': 'backupFor',
        'tag': 'tag'
    }

    def __init__(self, id=None, complex_bid_id=None, group_id=None, bid_type=None, tender=None, product_type=None, delivery_date=None, market=None, product_name=None, direction=None, time_interval=None, connecting_zone=None, resource_provider=None, status=None, receipt_timestamp=None, revision_timestamp=None, activation=None, min_quantity=None, offered_quantity=None, accepted_quantity=None, prices=None, technical_linkage=None, conditional_linkage=None, backup_for=None, tag=None):  # noqa: E501
        """Bid - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._complex_bid_id = None
        self._group_id = None
        self._bid_type = None
        self._tender = None
        self._product_type = None
        self._delivery_date = None
        self._market = None
        self._product_name = None
        self._direction = None
        self._time_interval = None
        self._connecting_zone = None
        self._resource_provider = None
        self._status = None
        self._receipt_timestamp = None
        self._revision_timestamp = None
        self._activation = None
        self._min_quantity = None
        self._offered_quantity = None
        self._accepted_quantity = None
        self._prices = None
        self._technical_linkage = None
        self._conditional_linkage = None
        self._backup_for = None
        self._tag = None
        self.discriminator = None
        self.id = id
        if complex_bid_id is not None:
            self.complex_bid_id = complex_bid_id
        if group_id is not None:
            self.group_id = group_id
        self.bid_type = bid_type
        self.tender = tender
        self.product_type = product_type
        self.delivery_date = delivery_date
        self.market = market
        self.product_name = product_name
        self.direction = direction
        self.time_interval = time_interval
        self.connecting_zone = connecting_zone
        self.resource_provider = resource_provider
        self.status = status
        self.receipt_timestamp = receipt_timestamp
        self.revision_timestamp = revision_timestamp
        if activation is not None:
            self.activation = activation
        if min_quantity is not None:
            self.min_quantity = min_quantity
        self.offered_quantity = offered_quantity
        if accepted_quantity is not None:
            self.accepted_quantity = accepted_quantity
        self.prices = prices
        if technical_linkage is not None:
            self.technical_linkage = technical_linkage
        if conditional_linkage is not None:
            self.conditional_linkage = conditional_linkage
        if backup_for is not None:
            self.backup_for = backup_for
        if tag is not None:
            self.tag = tag

    @property
    def id(self):
        """Gets the id of this Bid.  # noqa: E501


        :return: The id of this Bid.  # noqa: E501
        :rtype: BidIdentification
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this Bid.


        :param id: The id of this Bid.  # noqa: E501
        :type: BidIdentification
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def complex_bid_id(self):
        """Gets the complex_bid_id of this Bid.  # noqa: E501


        :return: The complex_bid_id of this Bid.  # noqa: E501
        :rtype: BidIdentification
        """
        return self._complex_bid_id

    @complex_bid_id.setter
    def complex_bid_id(self, complex_bid_id):
        """Sets the complex_bid_id of this Bid.


        :param complex_bid_id: The complex_bid_id of this Bid.  # noqa: E501
        :type: BidIdentification
        """

        self._complex_bid_id = complex_bid_id

    @property
    def group_id(self):
        """Gets the group_id of this Bid.  # noqa: E501


        :return: The group_id of this Bid.  # noqa: E501
        :rtype: BidIdentification
        """
        return self._group_id

    @group_id.setter
    def group_id(self, group_id):
        """Sets the group_id of this Bid.


        :param group_id: The group_id of this Bid.  # noqa: E501
        :type: BidIdentification
        """

        self._group_id = group_id

    @property
    def bid_type(self):
        """Gets the bid_type of this Bid.  # noqa: E501


        :return: The bid_type of this Bid.  # noqa: E501
        :rtype: BidType
        """
        return self._bid_type

    @bid_type.setter
    def bid_type(self, bid_type):
        """Sets the bid_type of this Bid.


        :param bid_type: The bid_type of this Bid.  # noqa: E501
        :type: BidType
        """
        if bid_type is None:
            raise ValueError("Invalid value for `bid_type`, must not be `None`")  # noqa: E501

        self._bid_type = bid_type

    @property
    def tender(self):
        """Gets the tender of this Bid.  # noqa: E501


        :return: The tender of this Bid.  # noqa: E501
        :rtype: TenderIdentification
        """
        return self._tender

    @tender.setter
    def tender(self, tender):
        """Sets the tender of this Bid.


        :param tender: The tender of this Bid.  # noqa: E501
        :type: TenderIdentification
        """
        if tender is None:
            raise ValueError("Invalid value for `tender`, must not be `None`")  # noqa: E501

        self._tender = tender

    @property
    def product_type(self):
        """Gets the product_type of this Bid.  # noqa: E501


        :return: The product_type of this Bid.  # noqa: E501
        :rtype: ProductType
        """
        return self._product_type

    @product_type.setter
    def product_type(self, product_type):
        """Sets the product_type of this Bid.


        :param product_type: The product_type of this Bid.  # noqa: E501
        :type: ProductType
        """
        if product_type is None:
            raise ValueError("Invalid value for `product_type`, must not be `None`")  # noqa: E501

        self._product_type = product_type

    @property
    def delivery_date(self):
        """Gets the delivery_date of this Bid.  # noqa: E501


        :return: The delivery_date of this Bid.  # noqa: E501
        :rtype: DeliveryDate
        """
        return self._delivery_date

    @delivery_date.setter
    def delivery_date(self, delivery_date):
        """Sets the delivery_date of this Bid.


        :param delivery_date: The delivery_date of this Bid.  # noqa: E501
        :type: DeliveryDate
        """
        if delivery_date is None:
            raise ValueError("Invalid value for `delivery_date`, must not be `None`")  # noqa: E501

        self._delivery_date = delivery_date

    @property
    def market(self):
        """Gets the market of this Bid.  # noqa: E501


        :return: The market of this Bid.  # noqa: E501
        :rtype: ReserveMarket
        """
        return self._market

    @market.setter
    def market(self, market):
        """Sets the market of this Bid.


        :param market: The market of this Bid.  # noqa: E501
        :type: ReserveMarket
        """
        if market is None:
            raise ValueError("Invalid value for `market`, must not be `None`")  # noqa: E501

        self._market = market

    @property
    def product_name(self):
        """Gets the product_name of this Bid.  # noqa: E501


        :return: The product_name of this Bid.  # noqa: E501
        :rtype: ProductName
        """
        return self._product_name

    @product_name.setter
    def product_name(self, product_name):
        """Sets the product_name of this Bid.


        :param product_name: The product_name of this Bid.  # noqa: E501
        :type: ProductName
        """
        if product_name is None:
            raise ValueError("Invalid value for `product_name`, must not be `None`")  # noqa: E501

        self._product_name = product_name

    @property
    def direction(self):
        """Gets the direction of this Bid.  # noqa: E501


        :return: The direction of this Bid.  # noqa: E501
        :rtype: Direction
        """
        return self._direction

    @direction.setter
    def direction(self, direction):
        """Sets the direction of this Bid.


        :param direction: The direction of this Bid.  # noqa: E501
        :type: Direction
        """
        if direction is None:
            raise ValueError("Invalid value for `direction`, must not be `None`")  # noqa: E501

        self._direction = direction

    @property
    def time_interval(self):
        """Gets the time_interval of this Bid.  # noqa: E501


        :return: The time_interval of this Bid.  # noqa: E501
        :rtype: TimeInterval
        """
        return self._time_interval

    @time_interval.setter
    def time_interval(self, time_interval):
        """Sets the time_interval of this Bid.


        :param time_interval: The time_interval of this Bid.  # noqa: E501
        :type: TimeInterval
        """
        if time_interval is None:
            raise ValueError("Invalid value for `time_interval`, must not be `None`")  # noqa: E501

        self._time_interval = time_interval

    @property
    def connecting_zone(self):
        """Gets the connecting_zone of this Bid.  # noqa: E501


        :return: The connecting_zone of this Bid.  # noqa: E501
        :rtype: ConnectingZone
        """
        return self._connecting_zone

    @connecting_zone.setter
    def connecting_zone(self, connecting_zone):
        """Sets the connecting_zone of this Bid.


        :param connecting_zone: The connecting_zone of this Bid.  # noqa: E501
        :type: ConnectingZone
        """
        if connecting_zone is None:
            raise ValueError("Invalid value for `connecting_zone`, must not be `None`")  # noqa: E501

        self._connecting_zone = connecting_zone

    @property
    def resource_provider(self):
        """Gets the resource_provider of this Bid.  # noqa: E501


        :return: The resource_provider of this Bid.  # noqa: E501
        :rtype: EIC
        """
        return self._resource_provider

    @resource_provider.setter
    def resource_provider(self, resource_provider):
        """Sets the resource_provider of this Bid.


        :param resource_provider: The resource_provider of this Bid.  # noqa: E501
        :type: EIC
        """
        if resource_provider is None:
            raise ValueError("Invalid value for `resource_provider`, must not be `None`")  # noqa: E501

        self._resource_provider = resource_provider

    @property
    def status(self):
        """Gets the status of this Bid.  # noqa: E501


        :return: The status of this Bid.  # noqa: E501
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this Bid.


        :param status: The status of this Bid.  # noqa: E501
        :type: str
        """
        if status is None:
            raise ValueError("Invalid value for `status`, must not be `None`")  # noqa: E501
        allowed_values = ["OFFERED", "ACCEPTED", "REJECTED"]  # noqa: E501
        if status not in allowed_values:
            raise ValueError(
                "Invalid value for `status` ({0}), must be one of {1}"  # noqa: E501
                .format(status, allowed_values)
            )

        self._status = status

    @property
    def receipt_timestamp(self):
        """Gets the receipt_timestamp of this Bid.  # noqa: E501

        Receipt time of the bid.  # noqa: E501

        :return: The receipt_timestamp of this Bid.  # noqa: E501
        :rtype: datetime
        """
        return self._receipt_timestamp

    @receipt_timestamp.setter
    def receipt_timestamp(self, receipt_timestamp):
        """Sets the receipt_timestamp of this Bid.

        Receipt time of the bid.  # noqa: E501

        :param receipt_timestamp: The receipt_timestamp of this Bid.  # noqa: E501
        :type: datetime
        """
        if receipt_timestamp is None:
            raise ValueError("Invalid value for `receipt_timestamp`, must not be `None`")  # noqa: E501

        self._receipt_timestamp = receipt_timestamp

    @property
    def revision_timestamp(self):
        """Gets the revision_timestamp of this Bid.  # noqa: E501

        Revision timestamp of the bid.  # noqa: E501

        :return: The revision_timestamp of this Bid.  # noqa: E501
        :rtype: datetime
        """
        return self._revision_timestamp

    @revision_timestamp.setter
    def revision_timestamp(self, revision_timestamp):
        """Sets the revision_timestamp of this Bid.

        Revision timestamp of the bid.  # noqa: E501

        :param revision_timestamp: The revision_timestamp of this Bid.  # noqa: E501
        :type: datetime
        """
        if revision_timestamp is None:
            raise ValueError("Invalid value for `revision_timestamp`, must not be `None`")  # noqa: E501

        self._revision_timestamp = revision_timestamp

    @property
    def activation(self):
        """Gets the activation of this Bid.  # noqa: E501


        :return: The activation of this Bid.  # noqa: E501
        :rtype: ActivationType
        """
        return self._activation

    @activation.setter
    def activation(self, activation):
        """Sets the activation of this Bid.


        :param activation: The activation of this Bid.  # noqa: E501
        :type: ActivationType
        """

        self._activation = activation

    @property
    def min_quantity(self):
        """Gets the min_quantity of this Bid.  # noqa: E501


        :return: The min_quantity of this Bid.  # noqa: E501
        :rtype: Quantity
        """
        return self._min_quantity

    @min_quantity.setter
    def min_quantity(self, min_quantity):
        """Sets the min_quantity of this Bid.


        :param min_quantity: The min_quantity of this Bid.  # noqa: E501
        :type: Quantity
        """

        self._min_quantity = min_quantity

    @property
    def offered_quantity(self):
        """Gets the offered_quantity of this Bid.  # noqa: E501


        :return: The offered_quantity of this Bid.  # noqa: E501
        :rtype: Quantity
        """
        return self._offered_quantity

    @offered_quantity.setter
    def offered_quantity(self, offered_quantity):
        """Sets the offered_quantity of this Bid.


        :param offered_quantity: The offered_quantity of this Bid.  # noqa: E501
        :type: Quantity
        """
        if offered_quantity is None:
            raise ValueError("Invalid value for `offered_quantity`, must not be `None`")  # noqa: E501

        self._offered_quantity = offered_quantity

    @property
    def accepted_quantity(self):
        """Gets the accepted_quantity of this Bid.  # noqa: E501


        :return: The accepted_quantity of this Bid.  # noqa: E501
        :rtype: Quantity
        """
        return self._accepted_quantity

    @accepted_quantity.setter
    def accepted_quantity(self, accepted_quantity):
        """Sets the accepted_quantity of this Bid.


        :param accepted_quantity: The accepted_quantity of this Bid.  # noqa: E501
        :type: Quantity
        """

        self._accepted_quantity = accepted_quantity

    @property
    def prices(self):
        """Gets the prices of this Bid.  # noqa: E501


        :return: The prices of this Bid.  # noqa: E501
        :rtype: Prices
        """
        return self._prices

    @prices.setter
    def prices(self, prices):
        """Sets the prices of this Bid.


        :param prices: The prices of this Bid.  # noqa: E501
        :type: Prices
        """
        if prices is None:
            raise ValueError("Invalid value for `prices`, must not be `None`")  # noqa: E501

        self._prices = prices

    @property
    def technical_linkage(self):
        """Gets the technical_linkage of this Bid.  # noqa: E501


        :return: The technical_linkage of this Bid.  # noqa: E501
        :rtype: TechnicalLinkage
        """
        return self._technical_linkage

    @technical_linkage.setter
    def technical_linkage(self, technical_linkage):
        """Sets the technical_linkage of this Bid.


        :param technical_linkage: The technical_linkage of this Bid.  # noqa: E501
        :type: TechnicalLinkage
        """

        self._technical_linkage = technical_linkage

    @property
    def conditional_linkage(self):
        """Gets the conditional_linkage of this Bid.  # noqa: E501


        :return: The conditional_linkage of this Bid.  # noqa: E501
        :rtype: ConditionalLinkage
        """
        return self._conditional_linkage

    @conditional_linkage.setter
    def conditional_linkage(self, conditional_linkage):
        """Sets the conditional_linkage of this Bid.


        :param conditional_linkage: The conditional_linkage of this Bid.  # noqa: E501
        :type: ConditionalLinkage
        """

        self._conditional_linkage = conditional_linkage

    @property
    def backup_for(self):
        """Gets the backup_for of this Bid.  # noqa: E501


        :return: The backup_for of this Bid.  # noqa: E501
        :rtype: BalancingServiceProvider
        """
        return self._backup_for

    @backup_for.setter
    def backup_for(self, backup_for):
        """Sets the backup_for of this Bid.


        :param backup_for: The backup_for of this Bid.  # noqa: E501
        :type: BalancingServiceProvider
        """

        self._backup_for = backup_for

    @property
    def tag(self):
        """Gets the tag of this Bid.  # noqa: E501


        :return: The tag of this Bid.  # noqa: E501
        :rtype: BidTag
        """
        return self._tag

    @tag.setter
    def tag(self, tag):
        """Sets the tag of this Bid.


        :param tag: The tag of this Bid.  # noqa: E501
        :type: BidTag
        """

        self._tag = tag

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Bid, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Bid):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
