# coding: utf-8

"""
    IP RL BSP API

    IP RL BSP API for participation in capacity/energy market tenders.  # noqa: E501

    OpenAPI spec version: 3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class BidModification(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'connecting_zone': 'ConnectingZone',
        'min_quantity': 'Quantity',
        'offered_quantity': 'Quantity',
        'prices': 'Prices',
        'activation': 'ActivationType',
        'technical_linkage': 'TechnicalLinkage',
        'conditional_linkage': 'ConditionalLinkage',
        'backup_for': 'BalancingServiceProvider'
    }

    attribute_map = {
        'connecting_zone': 'connectingZone',
        'min_quantity': 'minQuantity',
        'offered_quantity': 'offeredQuantity',
        'prices': 'prices',
        'activation': 'activation',
        'technical_linkage': 'technicalLinkage',
        'conditional_linkage': 'conditionalLinkage',
        'backup_for': 'backupFor'
    }

    def __init__(self, connecting_zone=None, min_quantity=None, offered_quantity=None, prices=None, activation=None, technical_linkage=None, conditional_linkage=None, backup_for=None):  # noqa: E501
        """BidModification - a model defined in Swagger"""  # noqa: E501
        self._connecting_zone = None
        self._min_quantity = None
        self._offered_quantity = None
        self._prices = None
        self._activation = None
        self._technical_linkage = None
        self._conditional_linkage = None
        self._backup_for = None
        self.discriminator = None
        if connecting_zone is not None:
            self.connecting_zone = connecting_zone
        if min_quantity is not None:
            self.min_quantity = min_quantity
        if offered_quantity is not None:
            self.offered_quantity = offered_quantity
        if prices is not None:
            self.prices = prices
        if activation is not None:
            self.activation = activation
        if technical_linkage is not None:
            self.technical_linkage = technical_linkage
        if conditional_linkage is not None:
            self.conditional_linkage = conditional_linkage
        if backup_for is not None:
            self.backup_for = backup_for

    @property
    def connecting_zone(self):
        """Gets the connecting_zone of this BidModification.  # noqa: E501


        :return: The connecting_zone of this BidModification.  # noqa: E501
        :rtype: ConnectingZone
        """
        return self._connecting_zone

    @connecting_zone.setter
    def connecting_zone(self, connecting_zone):
        """Sets the connecting_zone of this BidModification.


        :param connecting_zone: The connecting_zone of this BidModification.  # noqa: E501
        :type: ConnectingZone
        """

        self._connecting_zone = connecting_zone

    @property
    def min_quantity(self):
        """Gets the min_quantity of this BidModification.  # noqa: E501


        :return: The min_quantity of this BidModification.  # noqa: E501
        :rtype: Quantity
        """
        return self._min_quantity

    @min_quantity.setter
    def min_quantity(self, min_quantity):
        """Sets the min_quantity of this BidModification.


        :param min_quantity: The min_quantity of this BidModification.  # noqa: E501
        :type: Quantity
        """

        self._min_quantity = min_quantity

    @property
    def offered_quantity(self):
        """Gets the offered_quantity of this BidModification.  # noqa: E501


        :return: The offered_quantity of this BidModification.  # noqa: E501
        :rtype: Quantity
        """
        return self._offered_quantity

    @offered_quantity.setter
    def offered_quantity(self, offered_quantity):
        """Sets the offered_quantity of this BidModification.


        :param offered_quantity: The offered_quantity of this BidModification.  # noqa: E501
        :type: Quantity
        """

        self._offered_quantity = offered_quantity

    @property
    def prices(self):
        """Gets the prices of this BidModification.  # noqa: E501


        :return: The prices of this BidModification.  # noqa: E501
        :rtype: Prices
        """
        return self._prices

    @prices.setter
    def prices(self, prices):
        """Sets the prices of this BidModification.


        :param prices: The prices of this BidModification.  # noqa: E501
        :type: Prices
        """

        self._prices = prices

    @property
    def activation(self):
        """Gets the activation of this BidModification.  # noqa: E501


        :return: The activation of this BidModification.  # noqa: E501
        :rtype: ActivationType
        """
        return self._activation

    @activation.setter
    def activation(self, activation):
        """Sets the activation of this BidModification.


        :param activation: The activation of this BidModification.  # noqa: E501
        :type: ActivationType
        """

        self._activation = activation

    @property
    def technical_linkage(self):
        """Gets the technical_linkage of this BidModification.  # noqa: E501


        :return: The technical_linkage of this BidModification.  # noqa: E501
        :rtype: TechnicalLinkage
        """
        return self._technical_linkage

    @technical_linkage.setter
    def technical_linkage(self, technical_linkage):
        """Sets the technical_linkage of this BidModification.


        :param technical_linkage: The technical_linkage of this BidModification.  # noqa: E501
        :type: TechnicalLinkage
        """

        self._technical_linkage = technical_linkage

    @property
    def conditional_linkage(self):
        """Gets the conditional_linkage of this BidModification.  # noqa: E501


        :return: The conditional_linkage of this BidModification.  # noqa: E501
        :rtype: ConditionalLinkage
        """
        return self._conditional_linkage

    @conditional_linkage.setter
    def conditional_linkage(self, conditional_linkage):
        """Sets the conditional_linkage of this BidModification.


        :param conditional_linkage: The conditional_linkage of this BidModification.  # noqa: E501
        :type: ConditionalLinkage
        """

        self._conditional_linkage = conditional_linkage

    @property
    def backup_for(self):
        """Gets the backup_for of this BidModification.  # noqa: E501


        :return: The backup_for of this BidModification.  # noqa: E501
        :rtype: BalancingServiceProvider
        """
        return self._backup_for

    @backup_for.setter
    def backup_for(self, backup_for):
        """Sets the backup_for of this BidModification.


        :param backup_for: The backup_for of this BidModification.  # noqa: E501
        :type: BalancingServiceProvider
        """

        self._backup_for = backup_for

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(BidModification, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, BidModification):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
