# coding: utf-8

"""
    IP RL BSP API

    IP RL BSP API for participation in capacity/energy market tenders.  # noqa: E501

    OpenAPI spec version: 3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class BidGroup(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'market': 'ReserveMarket',
        'product_type': 'ProductType',
        'bid_type': 'BidType',
        'time_interval': 'TimeInterval',
        'tag': 'BidTag',
        'components': 'list[SimpleBid]'
    }

    attribute_map = {
        'market': 'market',
        'product_type': 'productType',
        'bid_type': 'bidType',
        'time_interval': 'timeInterval',
        'tag': 'tag',
        'components': 'components'
    }

    def __init__(self, market=None, product_type=None, bid_type=None, time_interval=None, tag=None, components=None):  # noqa: E501
        """BidGroup - a model defined in Swagger"""  # noqa: E501
        self._market = None
        self._product_type = None
        self._bid_type = None
        self._time_interval = None
        self._tag = None
        self._components = None
        self.discriminator = None
        self.market = market
        self.product_type = product_type
        self.bid_type = bid_type
        if time_interval is not None:
            self.time_interval = time_interval
        if tag is not None:
            self.tag = tag
        self.components = components

    @property
    def market(self):
        """Gets the market of this BidGroup.  # noqa: E501


        :return: The market of this BidGroup.  # noqa: E501
        :rtype: ReserveMarket
        """
        return self._market

    @market.setter
    def market(self, market):
        """Sets the market of this BidGroup.


        :param market: The market of this BidGroup.  # noqa: E501
        :type: ReserveMarket
        """
        if market is None:
            raise ValueError("Invalid value for `market`, must not be `None`")  # noqa: E501

        self._market = market

    @property
    def product_type(self):
        """Gets the product_type of this BidGroup.  # noqa: E501


        :return: The product_type of this BidGroup.  # noqa: E501
        :rtype: ProductType
        """
        return self._product_type

    @product_type.setter
    def product_type(self, product_type):
        """Sets the product_type of this BidGroup.


        :param product_type: The product_type of this BidGroup.  # noqa: E501
        :type: ProductType
        """
        if product_type is None:
            raise ValueError("Invalid value for `product_type`, must not be `None`")  # noqa: E501

        self._product_type = product_type

    @property
    def bid_type(self):
        """Gets the bid_type of this BidGroup.  # noqa: E501


        :return: The bid_type of this BidGroup.  # noqa: E501
        :rtype: BidType
        """
        return self._bid_type

    @bid_type.setter
    def bid_type(self, bid_type):
        """Sets the bid_type of this BidGroup.


        :param bid_type: The bid_type of this BidGroup.  # noqa: E501
        :type: BidType
        """
        if bid_type is None:
            raise ValueError("Invalid value for `bid_type`, must not be `None`")  # noqa: E501

        self._bid_type = bid_type

    @property
    def time_interval(self):
        """Gets the time_interval of this BidGroup.  # noqa: E501


        :return: The time_interval of this BidGroup.  # noqa: E501
        :rtype: TimeInterval
        """
        return self._time_interval

    @time_interval.setter
    def time_interval(self, time_interval):
        """Sets the time_interval of this BidGroup.


        :param time_interval: The time_interval of this BidGroup.  # noqa: E501
        :type: TimeInterval
        """

        self._time_interval = time_interval

    @property
    def tag(self):
        """Gets the tag of this BidGroup.  # noqa: E501


        :return: The tag of this BidGroup.  # noqa: E501
        :rtype: BidTag
        """
        return self._tag

    @tag.setter
    def tag(self, tag):
        """Sets the tag of this BidGroup.


        :param tag: The tag of this BidGroup.  # noqa: E501
        :type: BidTag
        """

        self._tag = tag

    @property
    def components(self):
        """Gets the components of this BidGroup.  # noqa: E501


        :return: The components of this BidGroup.  # noqa: E501
        :rtype: list[SimpleBid]
        """
        return self._components

    @components.setter
    def components(self, components):
        """Sets the components of this BidGroup.


        :param components: The components of this BidGroup.  # noqa: E501
        :type: list[SimpleBid]
        """
        if components is None:
            raise ValueError("Invalid value for `components`, must not be `None`")  # noqa: E501

        self._components = components

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(BidGroup, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, BidGroup):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
