# coding: utf-8

"""
    IP RL BSP API

    IP RL BSP API for participation in capacity/energy market tenders.  # noqa: E501

    OpenAPI spec version: 3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ConditionalLinkageItem(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'linked_to': 'BidIdentification',
        'condition': 'LinkageCondition'
    }

    attribute_map = {
        'linked_to': 'linkedTo',
        'condition': 'condition'
    }

    def __init__(self, linked_to=None, condition=None):  # noqa: E501
        """ConditionalLinkageItem - a model defined in Swagger"""  # noqa: E501
        self._linked_to = None
        self._condition = None
        self.discriminator = None
        self.linked_to = linked_to
        if condition is not None:
            self.condition = condition

    @property
    def linked_to(self):
        """Gets the linked_to of this ConditionalLinkageItem.  # noqa: E501


        :return: The linked_to of this ConditionalLinkageItem.  # noqa: E501
        :rtype: BidIdentification
        """
        return self._linked_to

    @linked_to.setter
    def linked_to(self, linked_to):
        """Sets the linked_to of this ConditionalLinkageItem.


        :param linked_to: The linked_to of this ConditionalLinkageItem.  # noqa: E501
        :type: BidIdentification
        """
        if linked_to is None:
            raise ValueError("Invalid value for `linked_to`, must not be `None`")  # noqa: E501

        self._linked_to = linked_to

    @property
    def condition(self):
        """Gets the condition of this ConditionalLinkageItem.  # noqa: E501


        :return: The condition of this ConditionalLinkageItem.  # noqa: E501
        :rtype: LinkageCondition
        """
        return self._condition

    @condition.setter
    def condition(self, condition):
        """Sets the condition of this ConditionalLinkageItem.


        :param condition: The condition of this ConditionalLinkageItem.  # noqa: E501
        :type: LinkageCondition
        """

        self._condition = condition

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ConditionalLinkageItem, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ConditionalLinkageItem):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
