# coding: utf-8

"""
    IP RL BSP API

    IP RL BSP API for participation in capacity/energy market tenders.  # noqa: E501

    OpenAPI spec version: 3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class DemandData(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'demand': 'int',
        'max_export': 'int',
        'core_share': 'int'
    }

    attribute_map = {
        'demand': 'demand',
        'max_export': 'maxExport',
        'core_share': 'coreShare'
    }

    def __init__(self, demand=None, max_export=None, core_share=None):  # noqa: E501
        """DemandData - a model defined in Swagger"""  # noqa: E501
        self._demand = None
        self._max_export = None
        self._core_share = None
        self.discriminator = None
        if demand is not None:
            self.demand = demand
        if max_export is not None:
            self.max_export = max_export
        if core_share is not None:
            self.core_share = core_share

    @property
    def demand(self):
        """Gets the demand of this DemandData.  # noqa: E501


        :return: The demand of this DemandData.  # noqa: E501
        :rtype: int
        """
        return self._demand

    @demand.setter
    def demand(self, demand):
        """Sets the demand of this DemandData.


        :param demand: The demand of this DemandData.  # noqa: E501
        :type: int
        """

        self._demand = demand

    @property
    def max_export(self):
        """Gets the max_export of this DemandData.  # noqa: E501


        :return: The max_export of this DemandData.  # noqa: E501
        :rtype: int
        """
        return self._max_export

    @max_export.setter
    def max_export(self, max_export):
        """Sets the max_export of this DemandData.


        :param max_export: The max_export of this DemandData.  # noqa: E501
        :type: int
        """

        self._max_export = max_export

    @property
    def core_share(self):
        """Gets the core_share of this DemandData.  # noqa: E501


        :return: The core_share of this DemandData.  # noqa: E501
        :rtype: int
        """
        return self._core_share

    @core_share.setter
    def core_share(self, core_share):
        """Sets the core_share of this DemandData.


        :param core_share: The core_share of this DemandData.  # noqa: E501
        :type: int
        """

        self._core_share = core_share

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(DemandData, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DemandData):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
