# coding: utf-8

"""
    IP RL BSP API

    IP RL BSP API for participation in capacity/energy market tenders.  # noqa: E501

    OpenAPI spec version: 3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class FrameworkAgreement(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'ResourceIdentification',
        'product_type': 'ProductType',
        'connecting_zone': 'ConnectingZone',
        'resource_provider': 'EIC',
        'contract_number': 'str',
        'validity_period': 'ContractValidityPeriod'
    }

    attribute_map = {
        'id': 'id',
        'product_type': 'productType',
        'connecting_zone': 'connectingZone',
        'resource_provider': 'resourceProvider',
        'contract_number': 'contractNumber',
        'validity_period': 'validityPeriod'
    }

    def __init__(self, id=None, product_type=None, connecting_zone=None, resource_provider=None, contract_number=None, validity_period=None):  # noqa: E501
        """FrameworkAgreement - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._product_type = None
        self._connecting_zone = None
        self._resource_provider = None
        self._contract_number = None
        self._validity_period = None
        self.discriminator = None
        if id is not None:
            self.id = id
        if product_type is not None:
            self.product_type = product_type
        if connecting_zone is not None:
            self.connecting_zone = connecting_zone
        if resource_provider is not None:
            self.resource_provider = resource_provider
        if contract_number is not None:
            self.contract_number = contract_number
        if validity_period is not None:
            self.validity_period = validity_period

    @property
    def id(self):
        """Gets the id of this FrameworkAgreement.  # noqa: E501


        :return: The id of this FrameworkAgreement.  # noqa: E501
        :rtype: ResourceIdentification
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this FrameworkAgreement.


        :param id: The id of this FrameworkAgreement.  # noqa: E501
        :type: ResourceIdentification
        """

        self._id = id

    @property
    def product_type(self):
        """Gets the product_type of this FrameworkAgreement.  # noqa: E501


        :return: The product_type of this FrameworkAgreement.  # noqa: E501
        :rtype: ProductType
        """
        return self._product_type

    @product_type.setter
    def product_type(self, product_type):
        """Sets the product_type of this FrameworkAgreement.


        :param product_type: The product_type of this FrameworkAgreement.  # noqa: E501
        :type: ProductType
        """

        self._product_type = product_type

    @property
    def connecting_zone(self):
        """Gets the connecting_zone of this FrameworkAgreement.  # noqa: E501


        :return: The connecting_zone of this FrameworkAgreement.  # noqa: E501
        :rtype: ConnectingZone
        """
        return self._connecting_zone

    @connecting_zone.setter
    def connecting_zone(self, connecting_zone):
        """Sets the connecting_zone of this FrameworkAgreement.


        :param connecting_zone: The connecting_zone of this FrameworkAgreement.  # noqa: E501
        :type: ConnectingZone
        """

        self._connecting_zone = connecting_zone

    @property
    def resource_provider(self):
        """Gets the resource_provider of this FrameworkAgreement.  # noqa: E501


        :return: The resource_provider of this FrameworkAgreement.  # noqa: E501
        :rtype: EIC
        """
        return self._resource_provider

    @resource_provider.setter
    def resource_provider(self, resource_provider):
        """Sets the resource_provider of this FrameworkAgreement.


        :param resource_provider: The resource_provider of this FrameworkAgreement.  # noqa: E501
        :type: EIC
        """

        self._resource_provider = resource_provider

    @property
    def contract_number(self):
        """Gets the contract_number of this FrameworkAgreement.  # noqa: E501


        :return: The contract_number of this FrameworkAgreement.  # noqa: E501
        :rtype: str
        """
        return self._contract_number

    @contract_number.setter
    def contract_number(self, contract_number):
        """Sets the contract_number of this FrameworkAgreement.


        :param contract_number: The contract_number of this FrameworkAgreement.  # noqa: E501
        :type: str
        """

        self._contract_number = contract_number

    @property
    def validity_period(self):
        """Gets the validity_period of this FrameworkAgreement.  # noqa: E501


        :return: The validity_period of this FrameworkAgreement.  # noqa: E501
        :rtype: ContractValidityPeriod
        """
        return self._validity_period

    @validity_period.setter
    def validity_period(self, validity_period):
        """Sets the validity_period of this FrameworkAgreement.


        :param validity_period: The validity_period of this FrameworkAgreement.  # noqa: E501
        :type: ContractValidityPeriod
        """

        self._validity_period = validity_period

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(FrameworkAgreement, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, FrameworkAgreement):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
