# coding: utf-8

"""
    IP RL BSP API

    IP RL BSP API for participation in capacity/energy market tenders.  # noqa: E501

    OpenAPI spec version: 3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class Quantity(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'quantity': 'float',
        'measure_unit': 'str'
    }

    attribute_map = {
        'quantity': 'quantity',
        'measure_unit': 'measureUnit'
    }

    def __init__(self, quantity=None, measure_unit=None):  # noqa: E501
        """Quantity - a model defined in Swagger"""  # noqa: E501
        self._quantity = None
        self._measure_unit = None
        self.discriminator = None
        self.quantity = quantity
        self.measure_unit = measure_unit

    @property
    def quantity(self):
        """Gets the quantity of this Quantity.  # noqa: E501

        Specify the quantity.  # noqa: E501

        :return: The quantity of this Quantity.  # noqa: E501
        :rtype: float
        """
        return self._quantity

    @quantity.setter
    def quantity(self, quantity):
        """Sets the quantity of this Quantity.

        Specify the quantity.  # noqa: E501

        :param quantity: The quantity of this Quantity.  # noqa: E501
        :type: float
        """
        if quantity is None:
            raise ValueError("Invalid value for `quantity`, must not be `None`")  # noqa: E501

        self._quantity = quantity

    @property
    def measure_unit(self):
        """Gets the measure_unit of this Quantity.  # noqa: E501

        The unit of measurement underlying the volume (MW per unit (code MAW), MWh per unit (code MWH)). The units of measurement are in accordance with UN/ECE Recommendation 20.  # noqa: E501

        :return: The measure_unit of this Quantity.  # noqa: E501
        :rtype: str
        """
        return self._measure_unit

    @measure_unit.setter
    def measure_unit(self, measure_unit):
        """Sets the measure_unit of this Quantity.

        The unit of measurement underlying the volume (MW per unit (code MAW), MWh per unit (code MWH)). The units of measurement are in accordance with UN/ECE Recommendation 20.  # noqa: E501

        :param measure_unit: The measure_unit of this Quantity.  # noqa: E501
        :type: str
        """
        if measure_unit is None:
            raise ValueError("Invalid value for `measure_unit`, must not be `None`")  # noqa: E501
        allowed_values = ["MAW"]  # noqa: E501
        if measure_unit not in allowed_values:
            raise ValueError(
                "Invalid value for `measure_unit` ({0}), must be one of {1}"  # noqa: E501
                .format(measure_unit, allowed_values)
            )

        self._measure_unit = measure_unit

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Quantity, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Quantity):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
